version: '3.8'

services:
  # 1. PostgreSQL - Database for Iceberg JDBC Catalog
  postgres-metastore:
    image: postgres:12
    container_name: postgres-metastore
    environment:
      POSTGRES_DB: metastore # We can still use this DB name
      POSTGRES_USER: hive # Or change to 'iceberg' if you prefer
      POSTGRES_PASSWORD: hivepassword
    volumes:
      - pg_metastore_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - iceberg_net

  # 2. MinIO - Our S3-compatible Storage (Keep this)
  minio:
    image: minio/minio:RELEASE.2023-09-07T02-05-02Z
    container_name: minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minio_secret_password
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - iceberg_net

  # 3. Zookeeper - Required by Kafka (Keep this)
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - iceberg_net

  # 4. Kafka - Our Streaming Platform (Keep this)
  kafka:
    image: confluentinc/cp-kafka:7.3.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    networks:
      - iceberg_net

  trino:
    image: trinodb/trino:448 # Using a specific recent version
    container_name: trino
    ports:
      - "8080:8080" # Trino UI and client port
    volumes:
      - ./trino_conf:/etc/trino # Mount our configuration files
    networks:
      - iceberg_net
    depends_on: # Ensures MinIO and Postgres are up before Trino tries to connect (helpful)
      - minio
      - postgres-metastore

volumes:
  pg_metastore_data:
  minio_data:

networks:
  iceberg_net:
    driver: bridge